# Pré-processamento - Roteiro da aula:

## 1 - Normalização dos Dados

Por reescala: define através de um valor mínimo e um valor máximo, um novo intervalo \\
onde os valores de um atributo estarão contidos (Exemplo: [0, 1]). \\
A normalização por reescala de um atributo $j$ de um objeto $x_i$ pode ser calculada como: \\

$$ x_{ij} = \frac{x_{ij} - min_j}{max_j - min_j} $$


Por padronização: os diferentes atributos contínuos poderão abranger diferentes intervalos, \\
mas deverão possuir os mesmos valores para alguma medida de posição e de espalhamento. \\
Essas medidas irão consistir na média e no desvio-padrão. \\

$$ x_{ij} = \frac{x_{ij} - \bar{x}_j}{\sigma_j} $$


## Estudo de Caso:
### Breast Cancer dataset

* https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data

In [1]:
import pandas as pd
import numpy as np

### Leitura da Base de Dados

In [2]:
# Faz a leitura da base de dados
def readDataset(dataset):
    return pd.read_csv(dataset)

### Limpeza dos Dados

#### Remoção de amostras NaN

In [3]:
def removeSamples(dataframe, feature):
  dataframe.dropna(subset=[feature], inplace=True)

#### Tratamento dos dados faltantes nas demais colunas

In [4]:
def fillSamples(dataframe):
  nan_columns = dataframe.columns[dataframe.isna().any()].tolist()
  for col in nan_columns:
    dataframe[col] = dataframe[col].fillna(dataframe[col].mean())

#### Normalização de atributos numéricos
* StandardScaler e MinMaxScaler

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [6]:
def stdScaler(dataframe, columns):
  scaler = StandardScaler()
  dataframe[columns] = scaler.fit_transform(dataframe[columns])

In [7]:
def minMax(dataframe, columns):
  scaler = MinMaxScaler()
  dataframe[columns] = scaler.fit_transform(dataframe[columns])

### Testando padronização StandardScaler

In [8]:
# Carrega a base de dados
df = readDataset('breast_cancer_missing.csv')

In [9]:
# Remove as amostras com diagnosis igual NaN
removeSamples(df, 'diagnosis')

In [10]:
# Armazena o nome das colunas com dados faltantes
nan_columns = df.columns[df.isna().any()].tolist()

In [11]:
# Substitui os dados faltantes pela média
fillSamples(df)

In [12]:
df.head()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,17.99,10.38,122.80,655.744196,0.1184,0.277600,0.300100,0.14710,0.181451,...,17.33,184.60,2019.0,0.1622,0.6656,0.27384,0.2654,0.46010,0.11890,malignant
2,84300903,19.69,21.25,130.00,1203.000000,0.1096,0.104296,0.090611,0.12790,0.206900,...,25.53,152.50,1709.0,0.1444,0.4245,0.45040,0.2430,0.29039,0.08758,malignant
3,84348301,11.42,20.38,77.58,386.100000,0.1425,0.283900,0.090611,0.10520,0.259700,...,26.50,98.87,567.7,0.2098,0.8663,0.68690,0.2575,0.66380,0.17300,malignant
4,84358402,20.29,14.34,135.10,1297.000000,0.1003,0.132800,0.090611,0.10430,0.180900,...,16.67,152.20,1575.0,0.1374,0.2050,0.40000,0.1625,0.23640,0.07678,malignant
5,843786,12.45,15.70,82.57,477.100000,0.1278,0.170000,0.157800,0.08089,0.208700,...,23.75,103.40,741.6,0.1791,0.5249,0.53550,0.1741,0.39850,0.12440,malignant

In [13]:
# Aplica a padronização StandarScaler nas colunas com dados faltantes
stdScaler(df, nan_columns)

In [14]:
# Verifica o resultado das 5 primeiras linhas
df.head()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,1.085817,-2.172329,1.283164,3.421260e-16,1.622464,3.508049e+00,2.736543e+00,2.562904,1.054117e-15,...,-1.484189,2.356961,2.106997,1.462564,2.759463,0.000000,2.375010,2.859841,2.124614,malignant
2,84300903,1.572820,0.481953,1.591406,1.646896e+00,0.968696,2.809158e-16,3.625689e-16,2.055453,9.665091e-01,...,-0.007520,1.374195,1.533224,0.597244,1.143226,0.886155,2.020424,0.000000,0.210300,malignant
3,84348301,-0.796309,0.269513,-0.652770,-8.114597e-01,3.412898,3.635574e+00,3.625689e-16,1.455497,2.971777e+00,...,0.167159,-0.267728,-0.579187,3.776567,4.104876,2.073151,2.249955,6.292452,5.431268,malignant
4,84358402,1.744704,-1.205359,1.809745,1.929777e+00,0.277781,5.769897e-01,3.625689e-16,1.431710,-2.093352e-02,...,-1.603042,1.365011,1.285206,0.256950,-0.328214,0.633198,0.746131,-0.909796,-0.449808,malignant
5,843786,-0.501242,-0.873269,-0.439141,-5.376068e-01,2.320808,1.329997e+00,8.776898e-01,0.812990,1.034871e+00,...,-0.328065,-0.129039,-0.257318,2.284133,1.816267,1.313273,0.929756,1.821801,2.460780,malignant

In [15]:
df.describe()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_radius,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension
count,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,...,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02,505.000000,5.050000e+02,5.050000e+02,5.050000e+02,5.050000e+02
mean,3.252912e+07,-3.587889e-16,4.836615e-16,1.547717e-16,1.477366e-16,4.361747e-16,1.266314e-16,4.221046e-17,-2.673329e-16,1.153753e-15,...,5.628061e-17,-2.567803e-16,-2.532628e-16,2.814031e-17,4.502449e-16,0.000000,7.035077e-17,-1.125612e-16,-1.969821e-16,-7.035077e-17
std,1.321784e+08,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,...,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00,1.000992,1.000992e+00,1.000992e+00,1.000992e+00,1.000992e+00
min,8.670000e+03,-2.067961e+00,-2.335932e+00,-2.099369e+00,-1.541533e+00,-2.529709e+00,-1.718872e+00,-1.183639e+00,-1.324913e+00,-2.865528e+00,...,-1.653720e+00,-2.440422e+00,-1.751368e+00,-1.287149e+00,-2.962722e+00,-1.519511,-1.374405e+00,-1.826200e+00,-2.256215e+00,-1.778582e+00
25%,8.692180e+05,-6.874492e-01,-6.998982e-01,-6.681818e-01,-6.712230e-01,-6.657259e-01,-7.166842e-01,-7.374097e-01,-7.519161e-01,-6.589734e-01,...,-6.906393e-01,-6.972322e-01,-7.052274e-01,-6.541474e-01,-5.937864e-01,-0.681494,-7.344818e-01,-7.662415e-01,-5.862505e-01,-6.692331e-01
50%,9.056860e+05,-1.488805e-01,8.675165e-16,-1.642911e-01,-2.198172e-01,1.031007e-15,-1.812859e-02,-1.379523e-01,-1.873765e-01,1.054117e-15,...,-2.264267e-01,-6.397782e-16,-1.627160e-01,-2.791588e-01,0.000000e+00,-0.159283,-8.100713e-02,-7.226615e-02,-3.352777e-02,-8.002533e-02
75%,8.812844e+06,4.183354e-01,5.649759e-01,4.140916e-01,1.500347e-01,5.972361e-01,4.535128e-01,3.251282e-01,4.916040e-01,4.879792e-01,...,3.875319e-01,5.597370e-01,3.883678e-01,1.680140e-01,5.194627e-01,0.423259,4.645589e-01,6.511525e-01,3.523671e-01,4.340034e-01
max,9.113205e+08,3.984920e+00,4.884594e+00,4.027378e+00,5.553061e+00,4.965599e+00,4.880464e+00,4.391616e+00,3.992754e+00,4.654228e+00,...,4.199637e+00,3.572501e+00,4.395971e+00,6.243716e+00,3.776567e+00,5.389956,4.909391e+00,2.780251e+00,6.292452e+00,5.431268e+00

### Testando normalização MinMaxScaler

In [16]:
# Carrega a base de dados
df = readDataset('breast_cancer_missing.csv')

In [17]:
# Remove as amostras com diagnosis igual NaN
removeSamples(df, 'diagnosis')

In [18]:
# Armazena o nome das colunas com dados faltantes
nan_columns = df.columns[df.isna().any()].tolist()

In [19]:
# Substitui os dados faltantes pela média
fillSamples(df)

In [20]:
df.head()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,17.99,10.38,122.80,655.744196,0.1184,0.277600,0.300100,0.14710,0.181451,...,17.33,184.60,2019.0,0.1622,0.6656,0.27384,0.2654,0.46010,0.11890,malignant
2,84300903,19.69,21.25,130.00,1203.000000,0.1096,0.104296,0.090611,0.12790,0.206900,...,25.53,152.50,1709.0,0.1444,0.4245,0.45040,0.2430,0.29039,0.08758,malignant
3,84348301,11.42,20.38,77.58,386.100000,0.1425,0.283900,0.090611,0.10520,0.259700,...,26.50,98.87,567.7,0.2098,0.8663,0.68690,0.2575,0.66380,0.17300,malignant
4,84358402,20.29,14.34,135.10,1297.000000,0.1003,0.132800,0.090611,0.10430,0.180900,...,16.67,152.20,1575.0,0.1374,0.2050,0.40000,0.1625,0.23640,0.07678,malignant
5,843786,12.45,15.70,82.57,477.100000,0.1278,0.170000,0.157800,0.08089,0.208700,...,23.75,103.40,741.6,0.1791,0.5249,0.53550,0.1741,0.39850,0.12440,malignant

In [21]:
# Aplica a normalização MinMaxScaler nas colunas com dados faltantes
minMax(df, nan_columns)

In [22]:
# Verifica o resultado das 5 primeiras linhas
df.head()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,0.521037,0.022658,0.552093,0.217283,0.553970,0.792037,0.703140,0.731113,0.381067,...,0.159030,0.668310,0.450698,0.656640,0.619292,0.218722,0.912027,0.598462,0.541370,malignant
2,84300903,0.601496,0.390260,0.602404,0.449417,0.466746,0.260461,0.212302,0.635686,0.509596,...,0.404612,0.508442,0.374508,0.528241,0.385375,0.359744,0.835052,0.263926,0.275856,malignant
3,84348301,0.210090,0.360839,0.236112,0.102906,0.792844,0.811361,0.212302,0.522863,0.776263,...,0.433663,0.241347,0.094008,1.000000,0.814012,0.548642,0.884880,1.000000,1.000000,malignant
4,84358402,0.629893,0.156578,0.638041,0.489290,0.374566,0.347893,0.212302,0.518390,0.378283,...,0.139263,0.506948,0.341575,0.477747,0.172415,0.319489,0.558419,0.157500,0.184300,malignant
5,843786,0.258839,0.202570,0.270980,0.141506,0.647140,0.461996,0.369728,0.402038,0.518687,...,0.351303,0.263908,0.136748,0.778547,0.482784,0.427716,0.598282,0.477035,0.587996,malignant

In [23]:
df.describe()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_radius,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension
count,5.050000e+02,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,...,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000,505.000000
mean,3.252912e+07,0.341649,0.323513,0.342656,0.217283,0.337506,0.260461,0.212302,0.249153,0.381067,...,0.282525,0.405863,0.284899,0.170916,0.439619,0.219917,0.218722,0.396444,0.263926,0.246688
std,1.321784e+08,0.165374,0.138631,0.163381,0.141092,0.133549,0.151681,0.179542,0.188239,0.133115,...,0.171012,0.166473,0.162833,0.132919,0.148531,0.144872,0.159297,0.217302,0.117093,0.138837
min,8.670000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.692180e+05,0.228075,0.226581,0.233597,0.122672,0.248687,0.151862,0.080037,0.107753,0.293434,...,0.164535,0.289907,0.170178,0.084054,0.351511,0.121285,0.101837,0.230103,0.195348,0.153866
50%,9.056860e+05,0.317052,0.323513,0.315841,0.186299,0.337506,0.257714,0.187559,0.213917,0.381067,...,0.243842,0.405863,0.258429,0.133848,0.439619,0.196864,0.205831,0.380756,0.260004,0.235588
75%,8.812844e+06,0.410762,0.401759,0.410244,0.238431,0.417187,0.329182,0.270619,0.341600,0.445960,...,0.348732,0.498952,0.348075,0.193227,0.516699,0.281175,0.292652,0.537801,0.305145,0.306884
max,9.113205e+08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000